In [1]:
import tensorflow as tf
import numpy as np
import os
import csv
import pandas as pd

In [2]:
! pip install kaggle

In [3]:
! mkdir ~/.kaggle

In [4]:
! cp kaggle.json ~/.kaggle/

In [5]:
! chmod 600 ~/.kaggle/kaggle.json

In [6]:
! kaggle datasets download lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

 78% 20.0M/25.7M [00:01<00:01, 4.95MB/s]
100% 25.7M/25.7M [00:01<00:00, 16.2MB/s]


In [7]:
os.getcwd()

'/content'

In [8]:
! unzip "/content/imdb-dataset-of-50k-movie-reviews.zip"

Archive:  /content/imdb-dataset-of-50k-movie-reviews.zip
  inflating: IMDB Dataset.csv        


In [9]:
df = pd.read_csv("/content/IMDB Dataset.csv")
print(df)

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]


In [10]:
null = pd.isnull(df["review"])
print(df[null])

Empty DataFrame
Columns: [review, sentiment]
Index: []


In [11]:
null = pd.isnull(df["sentiment"])
print(df[null])

Empty DataFrame
Columns: [review, sentiment]
Index: []


In [12]:
reviews = df['review'].tolist()
sentiments = df['sentiment'].tolist()

In [13]:
for i, sentiment in enumerate(sentiments):
  if sentiment == 'positive':
    sentiments[i] == 1.0
  else:
    sentiments[i] == 0.0

In [14]:
print(sentiments)

['positive', 'positive', 'positive', 'negative', 'positive', 'positive', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'positive', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'negative', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'ne

In [15]:
sentiments_final = np.array([])
for sentiment in sentiments:
  if sentiment == 'positive':
    sentiments_final = np.append(sentiments_final, 1.0)
  else:
    sentiments_final = np.append(sentiments_final, 0.0)

In [16]:
print(sentiments_final)
print(sentiments_final.shape)

[1. 1. 1. ... 0. 0. 0.]
(50000,)


In [17]:
train_reviews = reviews[:40000]
val_reviews = reviews[40000:48000]
test_reviews = reviews[48000:]

train_sentiments = np.array(sentiments_final[:40000])
val_sentiments = np.array(sentiments_final[40000:48000])
test_sentiments = np.array(sentiments_final[48000:])

In [18]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer.fit_on_texts(train_reviews)
words = tokenizer.word_index
print(len(words.items()))

112174


In [28]:
vocab_size=10000

In [19]:
train_sequences = tokenizer.texts_to_sequences(train_reviews)
print(train_sequences[0])

[28, 5, 2, 81, 2103, 46, 1074, 13, 101, 148, 40, 317, 2969, 410, 460, 27, 3174, 34, 24, 201, 15, 12, 7, 615, 49, 607, 17, 69, 8, 8, 2, 88, 149, 13, 3257, 69, 42, 2969, 14, 93, 5627, 3, 1, 135, 5, 570, 61, 272, 9, 201, 37, 2, 674, 140, 1713, 69, 12, 7, 22, 4, 119, 16, 2, 7871, 2258, 39, 1, 12, 119, 2496, 55, 5663, 17, 5183, 6, 1439, 378, 39, 570, 93, 7, 3731, 9, 2, 361, 354, 5, 2, 674, 8, 8, 10, 7, 432, 2969, 15, 13, 7, 2, 1, 357, 6, 2, 1, 6527, 2595, 1088, 1, 10, 2662, 1433, 21, 1, 535, 33, 4796, 2452, 5, 2, 1194, 118, 30, 2, 6894, 26, 2875, 1, 3, 393, 1, 35, 1, 7, 22, 305, 21, 2, 4797, 7406, 535, 7, 347, 6, 107, 1, 7466, 1, 1, 4722, 8341, 2307, 3, 51, 35, 1, 327, 9001, 6814, 1, 3, 8699, 1, 24, 112, 227, 242, 8, 8, 11, 59, 133, 2, 283, 1319, 5, 2, 119, 7, 688, 6, 2, 193, 13, 10, 273, 118, 81, 277, 598, 3068, 839, 180, 1353, 4333, 16, 2497, 1222, 839, 1434, 839, 886, 2969, 153, 976, 184, 2, 88, 410, 11, 124, 211, 3257, 69, 15, 35, 1614, 10, 14, 2291, 11, 422, 133, 11, 14, 1610, 16, 10, 

In [21]:
len_1500 = 0
len_1000 = 0
len_500 = 0
len_100 = 0
len_rem = 0
for i in range(len(train_sequences)):
  if len(train_sequences[i])>1500:
    len_1500+=1
  if len(train_sequences[i])>1000 and len(train_sequences[i])<=1500:
    len_1000+=1
  if len(train_sequences[i])>500 and len(train_sequences[i])<=1000:
    len_500+=1
  if len(train_sequences[i])>100 and len(train_sequences[i])<=500:
    len_100+=1
  if len(train_sequences[i])>0 and len(train_sequences[i])<=100:
    len_rem+=1

print(len_1500, len_1000, len_500, len_100, len_rem)

9 156 3091 32046 4698


In [22]:
maxlen = 600

In [24]:
train_sequences = tf.keras.preprocessing.sequence.pad_sequences(train_sequences, padding='post', truncating='post', maxlen=maxlen)

val_sequences = tokenizer.texts_to_sequences(val_reviews)
val_sequences = tf.keras.preprocessing.sequence.pad_sequences(val_sequences, padding='post', truncating='post', maxlen=maxlen)

test_sequences = tokenizer.texts_to_sequences(test_reviews)
test_sequences = tf.keras.preprocessing.sequence.pad_sequences(test_sequences, padding='post', truncating='post', maxlen=maxlen)

In [ ]:
vocab_size = 

In [25]:
print(train_sequences)
print(train_sequences.shape)
print(train_sentiments)
print(train_sentiments.shape)

[[ 28   5   2 ...   0   0   0]
 [  4 395 121 ...   0   0   0]
 [ 11 191  12 ...   0   0   0]
 ...
 [ 12 119   7 ...   0   0   0]
 [  2 193  13 ...   0   0   0]
 [ 11  26   6 ...   0   0   0]]
(40000, 600)
[1. 1. 1. ... 1. 0. 0.]
(40000,)


In [26]:
embedding_dim = 32

In [35]:
model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=maxlen),
                             tf.keras.layers.Flatten(),
                             tf.keras.layers.Dense(128, activation='tanh'),
                             tf.keras.layers.Dropout(0.3),
                             #tf.keras.layers.Dense(32, activation='tanh'),
                             #tf.keras.layers.Dropout(0.3),
                             tf.keras.layers.Dense(1, activation='sigmoid')
])



In [36]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.summary()
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=10)
history = model.fit(train_sequences, train_sentiments, epochs = 100, validation_data=(val_sequences, val_sentiments), callbacks = [callback])

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 600, 32)           320000    
_________________________________________________________________
flatten_3 (Flatten)          (None, 19200)             0         
_________________________________________________________________
dense_9 (Dense)              (None, 128)               2457728   
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 129       
Total params: 2,777,857
Trainable params: 2,777,857
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1250/1250 [==============================] - 40s 32ms/step - loss: 0.3706 - accuracy: 0.8288 - val